<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="ui fixed menu">
    <div class="ui container">
        <a href="#" class="header item">
            <img class="logo" src="/Agility/public/img/agile.jpg">
            Agility
        </a>
        <a href="#" class="item">Home </a>
        <a href="#" class="item">Inbox <div class="ui lightgrey tiny label">10</div></a>
        <a href="#" class="item">My Tasks <div class="ui lightgrey tiny label">5</div></a>
        <a href="#" class="item">Queued <div class="ui lightgrey tiny label">6</div></a>
        <a href="#" class="item">Involved <div class="ui lightgrey tiny label">3</div></a>
        <div class="ui simple dropdown item">
            Manage <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="#">Projects</a>
                <a class="item" href="#">Resources</a>
                <div class="divider"></div>
                <div class="header">Header Item</div>
                <div class="item">
                    <i class="dropdown icon"></i>
                    Sub Menu
                    <div class="menu">
                        <a class="item" href="#">Link Item</a>
                        <a class="item" href="#">Link Item</a>
                    </div>
                </div>
                <a class="item" href="#">Link Item</a>
            </div>
        </div>
    </div>    
</div>

<div class="page-header" style="margin-top: 8%;">
    <h1>
        New Project
    </h1>
</div>


<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "projects/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStarts" class="col-sm-2 control-label">Starts</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["starts", "size" => 30, "class" => "form-control", "id" => "fieldStarts"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-primary"]) ?>
        <?php echo $this->tag->linkTo(["projects/search", "Cancel", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
